# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/android'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'sampleMotionAppMotion'
  app.api_version = '21'

  app.gradle do
    # classpath 'com.android.tools.build:gradle:1.3.1'
    # plugin 'com.android.application'
    # library 'ReactAndroid', path: '../node_modules/react-native/ReactAndroid'
    library 'app', path: 'app'
  end
end
